include dracula.conf

# Fuente
font_size 12.0
font_family JetBrainsMono Nerd Font

# Padding (igual que Ghostty)
window_padding_width 12

# Sin decoraciones (similar a window-decoration = false)
hide_window_decorations yes

# Opacidad
background_opacity 1.0

# Cursor
cursor_shape block
cursor_blink_interval 0.5
shell_integration no-cursor

# Scrollback (similar)
scrollback_lines 3000

# Comportamiento
hide_mouse_cursor_when_typing yes

# Con esto cerramos kitty solo con la tecla esc
# map escape close_window

# con esto no pide condirmar al cerrar programas
confirm_os_window_close 0

