music_directory    "/mnt/vault/Music"
playlist_directory "/home/graplo/.config/mpd/playlists"

db_file            "/home/graplo/.local/share/mpd/database"
log_file           "/home/graplo/.local/share/mpd/log"
state_file         "/home/graplo/.local/share/mpd/state"
sticker_file       "/home/graplo/.local/share/mpd/sticker.sql"

bind_to_address    "127.0.0.1"
port               "6600"

auto_update        "yes"
restore_paused     "yes"
replaygain         "auto"

audio_output {
  type "pipewire"
  name "PipeWire Sound Server"
}
